---
on: push

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Init submodules
      env:
      run: |
        # Init ODF and OCS submodules
        git config --global user.name "GitHub Actions"
        git config --global user.email "41898282+github-actions@users.noreply.github.com"
        git config --global checkout.defaultRemote "origin"
        git submodule update --init

    - uses: actions/setup-go@v5
      with:
        go-version-file: odf-operator/go.mod

    - uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push docker images
      env:
        IMAGE_REGISTRY: docker.io
        REGISTRY_NAMESPACE: oussabe
      run: |
        # Init ODF and OCS submodules
        git config --global user.name "GitHub Actions"
        git config --global user.email "41898282+github-actions@users.noreply.github.com"
        git config --global checkout.defaultRemote "origin"
        git submodule update --init

        # Set build variable
        branch="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
        version="${branch#release-}"
        export IMAGE_TAG=$(date "+${version}-%Y-%m-%d-%H%M%S")
        export UX_BACKEND_OAUTH_FULL_IMAGE_NAME="quay.io/openshift/origin-oauth-proxy:$version"
        export OCS_BUNDLE_IMG="$IMAGE_REGISTRY/$REGISTRY_NAMESPACE/ocs-operator-bundle:$IMAGE_TAG"


        # Build OCS operator
        cd ocs-operator
        make ocs-operator
        podman push $IMAGE_REGISTRY/$REGISTRY_NAMESPACE/ocs-operator:$IMAGE_TAG
        make ocs-metrics-exporter
        podman push $IMAGE_REGISTRY/$REGISTRY_NAMESPACE/ocs-metrics-exporter:$IMAGE_TAG
        make operator-bundle
        podman push $IMAGE_REGISTRY/$REGISTRY_NAMESPACE/ocs-operator-bundle:$IMAGE_TAG
        make operator-catalog
        podman push $IMAGE_REGISTRY/$REGISTRY_NAMESPACE/ocs-operator-catalog:$IMAGE_TAG
        cd ../odf-operator

        # Build ODF operator
        make docker-build docker-push
        make bundle-build bundle-push
        make catalog-build catalog-push

