name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  ODF_UPSTREAM_REPO: "github.com/red-hat-storage/odf-operator"
  OCS_UPSTREAM_REPO: "github.com/red-hat-storage/odf-operator"


jobs:
  sync:
    name: Sync Upstream
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Create branches for the new ODF releases
        run: |
          # Set git config
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions@users.noreply.github.com"
          git config --global checkout.defaultRemote "origin"
          # Init ODF and OCS in the main branch
          git submodule update --init
          # Get the list of available ODF branches
          git remote add upstream https://${ODF_UPSTREAM_REPO}
          git fetch upstream
          git branch -r | grep 'upstream/release-[0-9]\.[0-9]\+$' | grep -v HEAD | while read line; do if [[ -z $(git ls-remote --heads origin "${line#upstream/}") ]]; then \
               git checkout -b "${line#upstream/}";\
               git submodule set-branch -b "${line#upstream/}" odf-operator;\
               git submodule set-branch -b "${line#upstream/}" ocs-operator;\
               git add .gitmodules;\
               git commit -m 'Set the branch for ODF and OCS submodules';\
               git submodule update --remote odf-operator;\
               git submodule update --remote ocs-operator;\
               git add odf-operator;\
               git add ocs-operator;\
               git commit -m 'Init ODF and OCS submodules';\
               git push --set-upstream origin "${line#upstream/}";\
           fi; done
          git remote remove upstream
          

      - name: Update existing branches
        run: |
          # Set git config
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions@users.noreply.github.com"
          git config --global checkout.defaultRemote "origin"
          git submodule update --init;\
          # Fetch all remote branches
          git fetch origin
          git branch -r | grep 'origin/release-[0-9]\.[0-9]\+$' | grep -v HEAD | while read line; do if [[ -z $(git ls-remote --heads origin "${line#origin/}") ]]; then \
              git checkout -b "${line#upstream/}";\
              git branch -u "${line}";\
              git reset --hard "${line}"
              git submodule update --remote;\
              git add .;\
              git commit -m 'Syncing submodules with upstream';\
              git push;\
           fi; done
